channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=24.1.2
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.2
  - pathlib==1.0.1
  - psutil==5.9.5
  - scikit-learn==1.3.1
  - scipy==1.14.1
  - xgboost==2.1.4
name: mlflow-env
